### ISSUE TITLE
Have a nicer splash screen

### ISSUE THREAD

**Issue by kelson42** [automactic/Kiwix#1]
The current splas screen simply show "kiwix". It's not really nice. We should have somethin better:
* Logo of Kiwix
* Logo of Kiwix fadding in
* A picture, like this for example https://commons.wikimedia.org/wiki/File:Kiwix_on_Android.jpg

**Comment by automactic** [comment]
I reckon we should follow [Apple iOS HIG guide](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/LaunchImages.html#//apple_ref/doc/uid/TP40006556-CH22-SW1), which doesn't suggest to use a splash screen. None of the stock app on iPhone use splash screen. (The lunch image mentioned is the "kiwix" and "BUILDXXX" screen.)  
I know a lot of apps use splash screens, and I am not oppose to it. But logo animate in is not a good idea. Because, the lunch image is static, cannot do any animation in it. Thus, the lunch image needs to be blank, then after the app is fully loaded, animate in the logo, leading to visually longer lunch time. A good example of splash screen is the official twitter app, which I like a lot.  
Why don't we just follow the official Apple HIG guide, and give it a try in the next beta?

**Comment by kelson42** [comment]
We should of course follow Apple guidelines and I'm (in general) against splash screens. I was simply under the impression there is one in the app! So what is this white screen appearing with "Kiwix" written in the middle at the start of the app?

**Comment by automactic** [comment]
This is called "lunch imagine". To quote the Apple HIG guide:

> The placeholder image gives users the impression that your app is fast and responsive because it appears instantly and is quickly replaced by the first screen of your app.  

So we just need to replace the lunch image with the first frame of the app. I just done it, you can see that in the next beta.

**Comment by kelson42** [comment]
Looks good to me. But just for my curiosity: what is the fundamental difference between a "lunch image" and a "splash screen"?

**Comment by automactic** [comment]
- splash screen: an entry experience
- lunch image: the first frame of the app when it starts, but shown to the user before the app is fully loaded, to create an illusion that the lunch is fast

**Comment by kelson42** [comment]
OK, thx for the explanation. I close the bug, looks like this is now fixed.
