### ISSUE TITLE
Downloading content should be put on the top of the list

### ISSUE THREAD

**Issue by kelson42** [automactic/Kiwix#21]
I think this would help users to have downloading content on the top of the "online" bookshelf. I see two reasons:
* You can "loose" the downloading item if you change the filter
* People want to check the downloading process and due to the large amount of availlable content, this might be difficult to find it in the list.

**Comment by automactic** [comment]
I think it would be a better idea to have a dedicated "downloading" tab, instead of moving them to the top of the list. Three reasons:
- If user have 2 or more languages checked in the filter, there will be 2 or more section in online tab. Moving to the top can cause confusion, since the book being downloaded might not belong to the section on the top of the list
- It can be painful when user accidentally tapped download and want to cancel.
- It creates a feeling that cell "escape" from user a lot. People don't usually expect a cell to fly around if they don't drag them around. It feels like the app is not listening to the user.

**Comment by kelson42** [comment]
OK, arguments (2) and (3) make sense to me. Now that most of the user will probably apply a filter to the content, the problem is not so big. I close the ticket.
