### ISSUE TITLE
Useless icon in the action bar?

### ISSUE THREAD

**Issue by kelson42** [automactic/Kiwix#6]
The second icon on the bottom action bar (with "2" in the middle) does not do anything for me. We should maybe replace it by the bookshelf icon

**Comment by automactic** [comment]
I think I will just delete it. That's some preparation for tabs in the future, the "2" will be able to change according to the number of active tabs in the future.

**Comment by kelson42** [comment]
I propose to replace it with the "bookshelf" button an remove the 2-level system settings. I think the tab system should be able to work without any additional action-bar button (for example by doing a long click on a link).

**Comment by automactic** [comment]
Oh, I think there has to be a 2nd-level menu, maybe not now, but definitely in the future, since we are gonna have more functions, such as fonts, font sizes, reading mode, rotation lock, etc. And something not accessed very often, like settings, maybe should be hidden in the 2nd level. 

I originally planned to replace the icon of the most right button in the action bar of main screen (It's now a setting gear), with a hamburger button.

**Comment by kelson42** [comment]
I'm not sure myself, but all your examples belongs to a settings panel IMO.

**Comment by automactic** [comment]
my examples?

**Comment by kelson42** [comment]
"such as fonts, font sizes, reading mode, rotation lock, etc." belongs to settings IMO.

**Comment by automactic** [comment]
Oh, but people might want to quickly adjust font size, especially reading mode, very often. Put them in a pop up menu will make them easier to find. Since they will appear as icons, people don't have search  through a list of settings.

I just think Bookshelf should not be a very visible place, since people will hardly open bookshelf again once they have download some books.

**Comment by kelson42** [comment]
I don't think people should have to do that often (size should be OK per default... and people which are weak, should only have to configure to display text a little bit larger than normal)... but you are in lead on this, I let you decide!

**Comment by automactic** [comment]
OK, I will do that the way I want for now, and we can see if it is satisfying and decide later.

**Comment by kelson42** [comment]
I have checked the bookmark feature on safari and it works with only one icon (with different behaviour for short-click and long-click). I think this should work in a similar way.

**Comment by automactic** [comment]
Oh, I never knew you could long press the bookmark button in safari. But this is a good thought. We may also need a tutorial to teach people these functions.

**Comment by automactic** [comment]
check this issue in BUILD 20150627

**Comment by kelson42** [comment]
I don't know what I should check, I don't see any change.

**Comment by automactic** [comment]
Sorry, I haven't uploaded BUILD 20150627 yet, which is the best build.

**Comment by kelson42** [comment]
OK, I have tested but this still does not work correctly IMO:
* long click shoudl add/remove bookmark and short click should show the history/boorkmars
* I click/longclick... but often it does not work

**Comment by kelson42** [comment]
done
